package com.uzumtech.finespenalties.constant.enums;

public enum PenaltyType {
    FINE, CONFISCATION, PAID_WITHDRAWAL, DEPRIVATION_OF_DRIVING_RIGHT, DEPRIVATION_OF_OTHER_RIGHT, ADMINISTRATIVE_ARREST, EXPULSION, COMPULSORY_WORKS
}
